<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.junln.framework</groupId>
        <artifactId>junln-dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>./junln-dependencies</relativePath>
    </parent>

    <artifactId>junln</artifactId>
    <packaging>pom</packaging>

    <name>Junln Framework</name>
    <description>
    </description>

    <properties>
        <!-- Maven Environment Versions -->
        <java.version>17</java.version>
        <resource.delimiter>@</resource.delimiter>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <maven.javadoc.failOnError>false</maven.javadoc.failOnError>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <modules>
        <module>junln-dependencies</module>
        <module>junln-bom</module>
        <module>junln-core</module>
        <module>junln-json</module>
        <module>junln-api-doc</module>
        <module>junln-validation</module>
        <module>junln-web</module>
        <module>junln-cache</module>
        <module>junln-auth</module>
        <module>junln-data</module>
        <module>junln-encrypt</module>
        <module>junln-security</module>
        <module>junln-ratelimiter</module>
        <module>junln-idempotent</module>
        <module>junln-trace</module>
        <module>junln-captcha</module>
        <module>junln-messaging</module>
        <module>junln-log</module>
        <module>junln-excel</module>
        <module>junln-storage</module>
        <module>junln-license</module>
        <module>junln-extension</module>
    </modules>

    <build>
        <plugins>
            <!-- 编译插件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <compilerArgument>-parameters</compilerArgument>
                </configuration>
            </plugin>
            <!-- 代码格式化插件 -->
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>apply</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <java>
                        <removeUnusedImports/>
                        <eclipse>
                            <file>.style/p3c-codestyle.xml</file>
                        </eclipse>
                        <licenseHeader>
                            <file>.style/license-header</file>
                        </licenseHeader>
                    </java>
                </configuration>
            </plugin>
            <!-- 统一版本号插件 -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>oss</flattenMode>
                    <pomElements>
                        <parent>expand</parent>
                        <properties>keep</properties>
                    </pomElements>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten-clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <url>https://github.com/orgs/junln-framework</url>
    <licenses>
        <license>
            <name>GNU LESSER GENERAL PUBLIC LICENSE</name>
            <url>http://www.gnu.org/licenses/lgpl.html</url>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>zjyau</id>
            <name>zjyau</name>
            <email>zjyau@hotmail.com</email>
            <roles>
                <role>Creator</role>
                <role>Java Development Engineer</role>
            </roles>
            <timezone>+8</timezone>
            <url>https://github.com/zjyau</url>
        </developer>
    </developers>
    <scm>
        <connection>scm:git:git@github.com:junln-framework/b18hfkzvw4.git</connection>
        <developerConnection>scm:git:git@github.com:junln-framework/b18hfkzvw4.git</developerConnection>
        <url>https://github.com/orgs/junln-framework/b18hfkzvw4</url>
    </scm>
</project>