<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.junln.framework</groupId>
        <artifactId>junln</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>junln-auth</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>Junln Framework 认证模块</description>

    <modules>
        <module>junln-auth-satoken</module>
        <module>junln-auth-justauth</module>
    </modules>

    <dependencies>
        <!-- 核心模块 -->
        <dependency>
            <groupId>cn.junln.framework</groupId>
            <artifactId>junln-core</artifactId>
        </dependency>
    </dependencies>
</project>